#!/usr/bin/env groovy
pipeline {
    agent none
    stages{
        stage('Build') {
            agent{
                docker { image 'maven:3.8.1-openjdk-17' }
            }
            steps{
                sh "mvn package -Dmaven.test.skip-true"
            }
        }
    }
}