#!/usr/bin/env groovy
pipeline {
    agent none
    stages{
        stage('Build') {
            agent{
                docker { image 'dwdraju/alpine-curl-jq' }
            }
            steps{
                sh "NOME=$(curl https://swapi.dev/api/people/1 | jq '.name')"
                sh "echo $NOME"
            }
        }
    }
}